// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAblQlufC1SjqTPGy9aHt23oUn_BtuXRbY',
    appId: '1:22606727953:web:94b57e39f102579a4c5ab0',
    messagingSenderId: '22606727953',
    projectId: 'e-wallet-bb26e',
    authDomain: 'e-wallet-bb26e.firebaseapp.com',
    storageBucket: 'e-wallet-bb26e.firebasestorage.app',
    measurementId: 'G-9WH8CTDVV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYGG8DUxSnLnjhwP84n6I_rT4rBjCbnsU',
    appId: '1:22606727953:android:1b7f3ae61510ad234c5ab0',
    messagingSenderId: '22606727953',
    projectId: 'e-wallet-bb26e',
    storageBucket: 'e-wallet-bb26e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7DIS69S-Req19y_CHFwYbqZc3GZ4cSuw',
    appId: '1:22606727953:ios:3edcb207637012724c5ab0',
    messagingSenderId: '22606727953',
    projectId: 'e-wallet-bb26e',
    storageBucket: 'e-wallet-bb26e.firebasestorage.app',
    iosBundleId: 'com.example.gocap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7DIS69S-Req19y_CHFwYbqZc3GZ4cSuw',
    appId: '1:22606727953:ios:3edcb207637012724c5ab0',
    messagingSenderId: '22606727953',
    projectId: 'e-wallet-bb26e',
    storageBucket: 'e-wallet-bb26e.firebasestorage.app',
    iosBundleId: 'com.example.gocap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAblQlufC1SjqTPGy9aHt23oUn_BtuXRbY',
    appId: '1:22606727953:web:9f6b79dd6c387ad34c5ab0',
    messagingSenderId: '22606727953',
    projectId: 'e-wallet-bb26e',
    authDomain: 'e-wallet-bb26e.firebaseapp.com',
    storageBucket: 'e-wallet-bb26e.firebasestorage.app',
    measurementId: 'G-2CY2VZMXH0',
  );
}
